// Records the M2 vertical slice as one clip: hunt → rewards → pin/craft → equip → hunt with the new skill → reload (persistence).
// Hunts use a shortened monster (debug hook) so the clip stays short; the full-HP hunt is covered by qa-m1.mjs.
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { readFileSync, mkdirSync } from 'node:fs';
const { chromium } = createRequire('/opt/node-tools/node_modules/')('playwright');
const BOT = readFileSync(new URL('./hunt-bot.js', import.meta.url), 'utf8');
const PORT = 4177;
const srv = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 2500));
mkdirSync('qa-artifacts/tmp', { recursive: true });
const VP = { width: 844, height: 390 };
const b = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await b.newContext({ viewport: VP, hasTouch: true, isMobile: true, recordVideo: { dir: 'qa-artifacts/tmp', size: VP } });
const page = await ctx.newPage();
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
await page.goto(`http://localhost:${PORT}/?debug=1`);
await page.waitForFunction(() => window.__wildforge?.app);
const hunt = async (target) => {
  await page.click('#btn-hunt'); await sleep(900);
  await page.check(`input[name=target][value=${target}]`); await sleep(500);
  await page.click('#btn-start');
  await page.evaluate(() => { const m = window.__wildforge.hunt.monster; m.hp = 60; m.partHp.fire_sac = 40; m.partHp.jaw = 30; });
  await page.evaluate(`window.__bot?.stop(); (${BOT})({})`);
  await page.waitForFunction(() => !document.getElementById('screen-results').hidden, null, { timeout: 150000, polling: 300 });
  await page.evaluate(() => window.__bot?.stop());
  await sleep(2500);
  await page.click('#btn-results-home'); await sleep(1200);
};
await sleep(1500);
await hunt('heat_bladder'); await hunt('heat_bladder');
await page.click('#btn-craft'); await sleep(1500);
await page.click('#craft-list .card:nth-child(2) button:has-text("ปักหมุด")'); await sleep(900);
await page.click('#craft-list .card:nth-child(2) button.primary'); await sleep(1500);
await page.selectOption('#slot-primary', 'ember'); await sleep(1500);
await page.click('#btn-craft-back'); await sleep(800);
await page.reload(); await page.waitForFunction(() => window.__wildforge?.app); await sleep(2000);
await page.click('#btn-hunt'); await sleep(1800);
await page.click('#btn-start'); await sleep(800);
await page.evaluate(() => { const h = window.__wildforge.hunt; h.monster.hp = 400; });
await page.evaluate(() => { const h = window.__wildforge.hunt; h.player.pos = { x: 800, y: 520 }; h.monster.phase = 'stagger'; h.monster.t = 0; h.monster.staggerDur = 4; h.monster.pos = { x: 800, y: 330 }; });
await sleep(600);
await page.evaluate(() => window.__wildforge.input.touch.moveY = -0.2); await sleep(500);
await page.evaluate(() => window.__wildforge.input.touch.moveY = 0);
await page.keyboard.press('KeyL'); await sleep(3600);
const v = page.video();
await ctx.close();
await v.saveAs('qa-artifacts/tmp/m2-loop.webm');
await b.close(); srv.kill();
console.log('recorded');
