// Records an M3 tour: first clear → unlocks → crab hunt → spear → capture (restrained) → bestiary. HP of animals is shortened for the clip.
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { readFileSync, mkdirSync } from 'node:fs';
const { chromium } = createRequire('/opt/node-tools/node_modules/')('playwright');
const BOT = readFileSync(new URL('./hunt-bot.js', import.meta.url), 'utf8');
const PORT = 4180;
const srv = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 2500));
mkdirSync('qa-artifacts/tmp', { recursive: true });
const VP = { width: 844, height: 390 };
const b = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await b.newContext({ viewport: VP, hasTouch: true, isMobile: true, recordVideo: { dir: 'qa-artifacts/tmp', size: VP } });
const page = await ctx.newPage();
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
await page.goto(`http://localhost:${PORT}/`);
await page.goto(`http://localhost:${PORT}/?debug=1`);
await page.waitForFunction(() => window.__wildforge?.app);
const shrink = () => page.evaluate(() => { const m = window.__wildforge.hunt.monster; m.hp = 90; for (const k of Object.keys(m.partHp)) m.partHp[k] = 40; });
const waitResults = async () => { await page.waitForFunction(() => !document.getElementById('screen-results').hidden, null, { timeout: 150000, polling: 300 }); await page.evaluate(() => window.__bot?.stop()); };
const hunt = async (mission, target) => {
  await page.click('#btn-hunt'); await sleep(700);
  await page.check(`input[name=mission][value=${mission}]`); await sleep(900);
  await page.check(`input[name=target][value=${target}]`); await sleep(500);
  await page.screenshot({ path: `qa-artifacts/m3-prep-${mission}.png` });
  await page.click('#btn-start'); await shrink();
  await page.evaluate(`window.__bot?.stop(); (${BOT})({ skill: true })`);
  await waitResults(); await sleep(3200);
};
await sleep(1500);
await hunt('hunt_gecko', 'fang'); await page.click('#btn-results-home'); await sleep(1200);
await hunt('hunt_crab', 'shell_scale'); await page.click('#btn-results-home'); await sleep(1000);
await page.click('#btn-craft'); await sleep(1500);
await page.selectOption('#slot-weapon', 'branch_spear'); await sleep(1500);
await page.click('#btn-craft-back'); await sleep(800);
// capture: animal at low HP, trap while it rests
await page.click('#btn-hunt'); await sleep(700);
await page.check('input[name=mission][value=capture_gecko]'); await sleep(1200);
await page.click('#btn-start'); await sleep(600);
await page.evaluate(() => { const h = window.__wildforge.hunt; h.monster.hp = Math.round(h.monster.def.hp * 0.2); });
await page.evaluate(`window.__bot?.stop(); (${BOT})({ capture: true })`);
await page.waitForFunction(() => !document.getElementById('screen-results').hidden, null, { timeout: 90000, polling: 300 });
await page.evaluate(() => window.__bot?.stop()); await sleep(3500);
await page.click('#btn-results-home'); await sleep(1800);
await page.click('#btn-bestiary'); await sleep(3500);
const v = page.video();
await ctx.close();
await v.saveAs('qa-artifacts/tmp/m3-tour.webm');
await b.close(); srv.kill();
console.log('recorded');
